server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/restaurants {
        proxy_pass http://restaurant-service:8000/restaurants;
    }

    location /api/menu {
        proxy_pass http://menu-service:8000/menu;
    }

    location /api/orders {
        proxy_pass http://order-service:8000/orders;
    }
}