apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: foodfast
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP