pipeline {
  agent any

  options {
    timestamps()
  }

  parameters {
    choice(
      name: 'ACTION',
      choices: ['deploy','destroy'],
      description: 'deploy or destroy full environment'
    )
  }

  environment {
    AWS_REGION = 'us-east-1'
    AWS_ACCOUNT_ID = '#############'

    TF_BUCKET = 'eric-foodfast-terraform-state'
    TF_LOCK_TABLE = 'foodfast-terraform-locks'
    TF_ENV = 'dev'

    TF_BOOTSTRAP_DIR = 'infra/bootstrap/state-backend'
    TF_ENV_DIR = 'infra/environments/dev'

    EKS_CLUSTER_NAME = 'foodfast-eks'
    K8S_NAMESPACE = 'foodfast'

    ECR_REGISTRY = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

    FRONTEND_IMAGE = "${ECR_REGISTRY}/frontend"
    RESTAURANT_IMAGE = "${ECR_REGISTRY}/restaurant-service"
    MENU_IMAGE = "${ECR_REGISTRY}/menu-service"
    ORDER_IMAGE = "${ECR_REGISTRY}/order-service"
    WORKER_IMAGE = "${ECR_REGISTRY}/notification-worker"
  }

  stages {

    stage('Checkout') {
      steps {
        deleteDir()

        git branch: 'main',
            credentialsId: 'github-ssh',
            url: 'git@github.com:Eric-Kay/fastfood.git'
      }
    }

    stage('Set image tag') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        script {
          COMMIT = sh(
            script: 'git rev-parse --short HEAD',
            returnStdout: true
          ).trim()

          env.TAG = "${BUILD_NUMBER}-${COMMIT}"
        }
      }
    }

    stage('Bootstrap backend if missing') {
        when { expression { params.ACTION == 'deploy' } }

        steps {
            withCredentials([
            string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
            string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
            ]) {

            sh '''
            set -eux

            BUCKET_EXISTS=false
            TABLE_EXISTS=false

            if aws s3api head-bucket --bucket ${TF_BUCKET} 2>/dev/null; then
                BUCKET_EXISTS=true
            fi

            if aws dynamodb describe-table \
                --table-name ${TF_LOCK_TABLE} \
                --region ${AWS_REGION} >/dev/null 2>&1; then
                TABLE_EXISTS=true
            fi

            if [ "$BUCKET_EXISTS" = "true" ] && [ "$TABLE_EXISTS" = "true" ]; then
                echo "terraform backend bucket and lock table already exist"
            else
                cd ${TF_BOOTSTRAP_DIR}

                terraform init

                terraform apply -auto-approve \
                -var="aws_region=${AWS_REGION}" \
                -var="bucket_name=${TF_BUCKET}" \
                -var="dynamodb_table_name=${TF_LOCK_TABLE}" \
                -var="environment=${TF_ENV}"
            fi
            '''
            }
        }
}

    stage('Create infrastructure') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          dir("${TF_ENV_DIR}") {
            sh '''
            set -eux

            terraform init -reconfigure

            terraform apply -auto-approve \
              -target=module.vpc \
              -target=module.eks \
              -target=module.ecr
            '''
          }
        }
      }
    }

    stage('configure kubectl') {
      when {
        expression { params.ACTION == 'deploy' || params.ACTION == 'destroy' }
      }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          sh '''
          set +e

          aws eks update-kubeconfig \
            --region ${AWS_REGION} \
            --name ${EKS_CLUSTER_NAME}

          kubectl get nodes

          exit 0
          '''
        }
      }
    }

    stage('Apply cluster addons') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          dir("${TF_ENV_DIR}") {
            sh '''
            set -eux

            terraform init -reconfigure
            terraform apply -auto-approve
            '''
          }
        }
      }
    }

    stage('Validate cluster addons') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          sh '''
          set -eux

          aws eks describe-addon \
            --cluster-name ${EKS_CLUSTER_NAME} \
            --addon-name aws-ebs-csi-driver \
            --region ${AWS_REGION} \
            --query addon.status \
            --output text | tee /tmp/ebs_addon_status.txt

          test "$(cat /tmp/ebs_addon_status.txt)" = "ACTIVE"

          kubectl get pods -n kube-system | grep -i ebs
          '''
        }
      }
    }

    stage('Install metrics-server') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          sh '''
          set -eux

          helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/ || true
          helm repo update

          helm upgrade --install metrics-server metrics-server/metrics-server \
            -n kube-system \
            --set args[0]=--kubelet-insecure-tls

          kubectl get pods -n kube-system | grep metrics-server
          '''
        }
      }
    }

    stage('Validate metrics-server') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          sh '''
          set -eux
          kubectl top nodes
          '''
        }
      }
    }

    stage('build images') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        sh '''
        set -eux

        docker build -t ${FRONTEND_IMAGE}:${TAG} apps/frontend
        docker build -t ${RESTAURANT_IMAGE}:${TAG} apps/restaurant-service
        docker build -t ${MENU_IMAGE}:${TAG} apps/menu-service
        docker build -t ${ORDER_IMAGE}:${TAG} apps/order-service
        docker build -t ${WORKER_IMAGE}:${TAG} apps/notification-worker
        '''
      }
    }

    stage('push images') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          sh '''
          set -eux

          aws ecr get-login-password --region ${AWS_REGION} \
          | docker login \
            --username AWS \
            --password-stdin ${ECR_REGISTRY}

          docker push ${FRONTEND_IMAGE}:${TAG}
          docker push ${RESTAURANT_IMAGE}:${TAG}
          docker push ${MENU_IMAGE}:${TAG}
          docker push ${ORDER_IMAGE}:${TAG}
          docker push ${WORKER_IMAGE}:${TAG}
          '''
        }
      }
    }

    stage('deploy k8s') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          sh '''
          set -eux

          sed -i "s|${FRONTEND_IMAGE}:latest|${FRONTEND_IMAGE}:${TAG}|g" k8s/frontend/deployment.yaml
          sed -i "s|${RESTAURANT_IMAGE}:latest|${RESTAURANT_IMAGE}:${TAG}|g" k8s/restaurant-service/deployment.yaml
          sed -i "s|${MENU_IMAGE}:latest|${MENU_IMAGE}:${TAG}|g" k8s/menu-service/deployment.yaml
          sed -i "s|${ORDER_IMAGE}:latest|${ORDER_IMAGE}:${TAG}|g" k8s/order-service/deployment.yaml
          sed -i "s|${WORKER_IMAGE}:latest|${WORKER_IMAGE}:${TAG}|g" k8s/notification-worker/deployment.yaml

          pwd
          ls -la
          find . -maxdepth 3 -type f | sort | grep '^./k8s/' || true

          kubectl apply -f k8s/namespace.yaml

          kubectl apply -f k8s/postgres/
          kubectl apply -f k8s/redis/
          kubectl apply -f k8s/rabbitmq/

          kubectl apply -f k8s/restaurant-service/
          kubectl apply -f k8s/menu-service/
          kubectl apply -f k8s/order-service/
          kubectl apply -f k8s/notification-worker/
          kubectl apply -f k8s/frontend/

          kubectl apply -f k8s/ingress/
          kubectl apply -f k8s/autoscaling/
          '''
        }
      }
    }

    stage('verify rollout') {
      when { expression { params.ACTION == 'deploy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          sh '''
          set -eux

          kubectl rollout status deployment/frontend -n ${K8S_NAMESPACE}
          kubectl rollout status deployment/order-service -n ${K8S_NAMESPACE}
          kubectl rollout status deployment/menu-service -n ${K8S_NAMESPACE}
          kubectl rollout status deployment/restaurant-service -n ${K8S_NAMESPACE}
          kubectl rollout status deployment/notification-worker -n ${K8S_NAMESPACE}

          kubectl get pods -n ${K8S_NAMESPACE}
          kubectl get svc -n ${K8S_NAMESPACE}
          kubectl get pvc -n ${K8S_NAMESPACE}
          kubectl get hpa -n ${K8S_NAMESPACE}
          '''
        }
      }
    }

    stage('destroy k8s workloads') {
      when { expression { params.ACTION == 'destroy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          sh '''
          set +e

          aws eks update-kubeconfig \
            --region ${AWS_REGION} \
            --name ${EKS_CLUSTER_NAME}

          kubectl delete namespace ${K8S_NAMESPACE}

          exit 0
          '''
        }
      }
    }

    stage('destroy infra') {
      when { expression { params.ACTION == 'destroy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          dir("${TF_ENV_DIR}") {
            sh '''
            set +e

            terraform init -reconfigure
            terraform destroy -auto-approve

            exit 0
            '''
          }
        }
      }
    }

    stage('delete backend') {
      when { expression { params.ACTION == 'destroy' } }

      steps {
        withCredentials([
          string(credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {

          sh '''
          set +e

          aws s3 rm s3://${TF_BUCKET} --recursive

          aws s3api delete-bucket \
            --bucket ${TF_BUCKET} \
            --region ${AWS_REGION}

          aws dynamodb delete-table \
            --table-name ${TF_LOCK_TABLE} \
            --region ${AWS_REGION}

          exit 0
          '''
        }
      }
    }
  }

  post {
    always {
      sh 'docker image prune -f || true'
      cleanWs()
    }
  }
}
